### ISSUE TITLE
The crip export don't trow error when permission issue

### ISSUE THREAD

**Issue by yodatak** [Hakky54/certificate-ripper#20] opened 2024-01-22 14:46 UTC
thanks for your tool so usefull to boostrap cerets to wsl2
In fedora wsl2, i must run 

`sudo crip export pem -u=https://github.com --combined=true -d /etc/pki/ca-trust/source/anchors/fullchain.pem`
because 

`/etc/pki/ca-trust/source/anchors$ sudo crip export pem -u=https://github.com --combined=true -d /etc/pki/ca-trust/source/anchors/fullchain.pem`

```
Certificate ripper statistics:
- Certificate count

  * 4: https://github.com
         [cn=githubcom_o=github_-inc_l=san-francisco_st=california_c=us]
         [cn=XXX-dpi_ou=XXX=XXXX]
         [cn=XXX-subca_dc=#XXXX=#XXX]
         [cn=XXXX-rootca]

Extracted 4 certificates.
It has been exported to /etc/pki/ca-trust/source/anchors/fullchain.pem
```
I dont have any error but it don't create a file :/

**Comment by Hakky54** [comment] 2024-01-23 01:12
Thank you for your kind words ❤️ 

I have install fedore on my wsl as instructed from this tutorial: https://www.linuxfordevices.com/tutorials/linux/install-fedora-on-windows

I didn't used the `sudo` prefix and it already worked. See here my screenshots:

![Schermafbeelding 2024-01-23 020844](https://github.com/Hakky54/certificate-ripper/assets/16032204/569d20a9-d90c-430a-b979-2f57e09b7d17)

![Schermafbeelding 2024-01-23 020611](https://github.com/Hakky54/certificate-ripper/assets/16032204/918ea7ad-901d-4457-a761-3216409a42db)

I tried with the same setup as you have, however I don't have the issue. Even using `sudo` works. So I am not able to reproduce the issue. Do I need to configure fedora wsl differently?

**Comment by yodatak** [comment] 2024-01-23 07:14
Try with a simple user not root without sudo

**Comment by Hakky54** [comment] 2024-01-23 21:46
Yes, I am now able to reproduce it. So it should fail with a regular user trying to write to a directory which it does not have access without using sudo. Crip tells it exported it however there is no fail generated. So it actually failed but the error is missing in the console output. I see also the bug in the code, so I will make a fix for this. Thank you for pointing out this issue!

**Closed** 2024-01-24 07:07 UTC

**Comment by Hakky54** [comment] 2024-02-12 22:06
@yodatak  I have published the new artifacts in the releases section. The latest changes are now in version 2.3.0
